# docker run --rm \
#   -v "$PWD:/srv/jekyll" \
#   -e BUNDLE_PATH="/srv/jekyll/.bundles_cache" \
#   -p 4000:4000 \
#   jekyll/builder:3.8 \
#   bash -c "gem install bundler && bundle install && bundle exec jekyll serve --host 0.0.0.0 --verbose --config _config.yml"


version: '3'

services:
  jekyll-serve:
    image: jekyll/jekyll:latest
    command: jekyll serve --watch --force_polling --verbose
    ports:
      - 4000:4000
    volumes:
      - '.:/srv/jekyll'